export const GET_CONVERSATIONS = "GET_CONVERSATIONS";
export const SET_MESSAGE = "SET_MESSAGE";
export const ADD_ONLINE_USER = "ADD_ONLINE_USER";
export const REMOVE_OFFLINE_USER = "REMOVE_OFFLINE_USER";
export const SET_SEARCHED_USERS = "SET_SEARCHED_USERS";
export const CLEAR_SEARCHED_USERS = "CLEAR_SEARCHED_USERS";
export const ADD_CONVERSATION = "ADD_CONVERSATION";
